요약 - 앨범 이름 등록 추가, 로그인 시 앨범 목록으로 들어가게끔 구현 1. 앨범 이름 등록 추가, 추후 애니메이션 디자인 할때 앨범 표지에 나오도록 할 예정 2. 로그인 시 바로 사진 등록 화면이 아닌 앨범 목록으로 들어가게끔 하여 앨범 목록 조회, 사진 등록 분기되도록 구현
--오류 해결
	1. 앨범 이름 입력 추가하여 서버에 보내서 서버쪽에서 받을때 문제 생김, 앨범 이름 때문은 아니고, mabatis 설정탓
		--> org.mybatis.spring.MyBatisSystemException: nested exception is
org.apache.ibatis.builder.BuilderException: Error evaluating expression
'pwdRequired.equalsIgnoreCase('n') or pwdRequired == null'. Cause:
org.apache.ibatis.ognl.MethodFailedException: Method "equalsIgnoreCase"
failed for object n [java.lang.NoSuchMethodException:
java.lang.Character.equalsIgnoreCase(java.lang.Character)]]을(를) 발생시켰습니다.
		에러 발생, photo-mapping.xml에서 mybatis 동적 쿼리 설정중에 문제가 생긴듯 하다.
		--> 동적쿼리 if문에 pwdRequired.equalsIgnoreCase('n') 가 아니라
pwdRequired.equals('n') 로 사용했다.
 	2. 칸 띄고 사진 등록하면 사진 개수(페이지) 씹힘
		--> Object.keys(imgAlbumDic) 의 길이가 아니고 Object.keys(imgAlbumDic) 속의 사진
번호의 최댓값을 찾아서 해당 번호 기준으로
			페이지 수를 구했다. 해결

	3. 관리자로 로그인했을때 앨범 목록 뜨기
		--> 거기서 앨범 등록/보기 가기
		--> albumList.do 로직 처리중 getAllAlbum() photo-mapping에서 문제 생긴것 같다.
		org.mybatis.spring.MyBatisSystemException: nested exception is
org.apache.ibatis.reflection.ReflectionException: There is no getter for
property named 'userId' in 'class java.lang.String']을(를) 발생시켰습니다.
		-->
			<select id="getAllAlbum" resultType="album">
				SELECT * FROM albums
				<if test="userid != null and !userid.isEmpty()">
				WHERE userid=#{userid}
				</if>
			</select>
			여기에서 쿼리문 자체에서 userid를 못찾는줄 알았는데, mybatis 동적 쿼리인 if 문에서 userid를
못찾는것이었다. dao에서 매개변수로 userid만 String으로 넘겼는데,
			mybatis에서는 userid를 찾을때 getter 를 사용해서 가져오기 때문에, String타입인
userid.getUserid()를 했으니 당연히 오류가 난것이었다.
			따라서 if문을 쓰려면 String타입인 userid 하나만 달랑 보내는것이 아닌 getter 메소드가 있는 vo 객체에
userid를 넣어서 보내야 했다.
		--> userid String값을 AlbumVO에 담아 넘기고 해결